name: Daemon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: daemon/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('daemon/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Build
        run: mise run build:daemon

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: daemon/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('daemon/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Run tests
        run: mise run test:daemon

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: daemon/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('daemon/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Check formatting with Quokka
        run: mise run lint:daemon
